### ISSUE TITLE
base58CheckEncode: TypeError 

### ISSUE THREAD

**Issue by BryceMindLab** [PaulGregor/Bitcoin-Keys-Generator#1]
When running `python3 generators.py` I receive the following error in the `base58CheckEncode` method:

`privateKeyToWif: 
Traceback (most recent call last):
  File "generators.py", line 121, in <module>
    print(privateKeyToWif(pr_key))
  File "generators.py", line 79, in privateKeyToWif
    return base58CheckEncode(b'\x80', unhexlify(key_hex))
  File "generators.py", line 48, in base58CheckEncode
    return '1' * countLeadingZeroes(result) + base58.b58encode(result)
TypeError: must be str, not bytes
`

I can only seem to resolve the error by changing the return to `return str(countLeadingZeroes(result)) + str(base58.b58encode(result))`

ecdsa: (v0.13)
base58: (v1.0.0)

**Comment by PaulGregor** [comment]
Hello. I've updated generators.py to the latest version.

**Comment by BryceMindLab** [comment]
Thanks, the new code is much cleaner, but unfortunately I'm still receiving the same error:

`File "generators.py", line 32, in base58CheckEncode
    return '1' * countLeadingZeroes(result) + base58.b58encode(result)
TypeError: must be str, not bytes
`

**Comment by PaulGregor** [comment]
I've tested again, and on different machine. I don't have any errors. I'm using python 3.6
