### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by falcon141** [PaulGregor/Bitcoin-Keys-Generator#2]
How to run this script

**Comment by PaulGregor** [comment]
> How to run this script

Hi. Use python 3.6, open `generators.py,` set number you want to `int_to_address()` , for example: `int_to_address(1256267)` 
And just run  `python generators.py`

**Comment by falcon141** [comment]
I run in termux

Pada tanggal Rab, 29 Jan 2020 15:38, Paul <notifications@github.com>
menulis:

**Comment by PaulGregor** [comment]
> I run in termux 

I dont know about termux. But try to install python there, also install requirements `python -m pip install -r requirements.txt` and then run the script.

**Comment by PaulGregor** [comment]
I've updated code. Now you may use `python generators 123`  to convert number `123` to bitcoin address
