### ISSUE TITLE
You will go to jail for this!

### ISSUE THREAD

**Issue by AlinaSec** [PaulGregor/Bitcoin-Keys-Generator#4]
You really thing this is going to work for you? You will go jail and return all the money to people that you scammed for!

**Comment by PaulGregor** [comment]
You're claiming to be "specialist in cyber risk mitigation" but you don't even understand Bitcoin's basic principles and how it works. So pathetic.

**Comment by AlinaSec** [comment]
Lets see how you gonna sing behind the bars.
